esign/urls.py
from django.conf import settings
from django.urls import path
from django.conf.urls import handler403, handler404, handler500
from django.conf.urls.static import static
from . import views

app_name = 'esign'
urlpatterns = [

    ###############      LANDING PAGES      ################
    path('', views.index, name='index'),
    path('get_document_details/', views.get_document_details, name='get_document_details'),
    path('viewDoc/<str:docID>', views.viewDoc, name='viewDoc'),
    path('save_pdf_to_db/', views.save_pdf_to_db, name='save_pdf_to_db'),

    ###############      Authentication + MFA      ################
    path('login/', views.login_request, name='login'),
    path('resend_totp/', views.resend_totp, name='resend_totp'),
    path('verify_totp/', views.verify_totp, name='verify_totp'),
    path('logout/', views.logout_request, name='logout'),
    path('xlogin/', views.xlogin, name='xlogin'),
    
    path('add_image_signature/', views.add_image_signature, name='add_image_signature'),

    ###############      MANAGEMENT      ################
    path('management/<str:hashed_url>/', views.management, name='management'),
    path('get_names_emails/', views.get_names_emails_for_company, name='get_names_emails'),
    path('signer_email/', views.signer_email, name='signer_email'),
    path('owner_email/', views.owner_email, name='owner_email'),
    path('update_document_title/<str:document_id>/', views.update_document_title, name='update_document_title'),
    path('update_due/', views.update_due, name='update_due'),
    path('update_permission/', views.update_permission, name='update_permission'),
    path('update_role/', views.update_role, name='update_role'),
    path('delete_permission/', views.delete_permission, name='delete_permission'),
    path('add_remark/', views.add_remark, name='add_remark'),

    ###############      ESIGNATURE      ################
    path('sign/<str:hashed_url>/', views.sign, name='sign'),
    path('face_detection/', views.face_detection_view, name='face_detection'),
    path('home/', views.homw_view, name='home'),
    path('classify/', views.find_user_view, name='classify'),
    path('draw/', views.draw_signature, name='draw'),
    path('type/', views.type_signature, name='type'),
    path('upload/', views.upload_profile, name='upload'),

    ###############      PROFILE      ################
    path('profile/', views.profile, name='profile'),

    ###############      SESSION      ################
    path('check_session/', views.check_session, name='check_session'),


    # path('test/', views.test, name='test'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = "esign.views.handler403"  # Set the handler403 for the app
handler404 = "esign.views.handler404"  # Set the handler404 for the app
handler500 = "esign.views.handler500"  # Set the handler500 for the app

myproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path("esign/", include("esign.urls")),
    path("admin/", admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

esign/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class LoginForm(forms.Form):
    UID = forms.CharField(max_length=100)
    psw = forms.CharField(widget=forms.PasswordInput)

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('title','pdf_file')

class SignatureForm(forms.ModelForm):
    class Meta:
        model = Signature
        fields = ('docID','signature')

class OrganizationForm(forms.ModelForm):
    class Meta:
        model = Organization
        fields = ('orgID','name','email','address','phone_no')

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ("email", "username", "orgID", "position")


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ("email",)

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('photo', 'bio')

esign/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import *
from .forms import *
from django.utils import timezone
from django.contrib.auth import login, logout, authenticate
from django.http import JsonResponse
from datetime import datetime
from django.db.models import F
from django.core.mail import send_mail
from django.contrib import messages
import re
import pyotp
from django.contrib.auth.decorators import login_required
import PyPDF2
from django.shortcuts import render
from django.core.files.storage import FileSystemStorage
import os
from django.conf import settings
from django.http import HttpResponse
from PyPDF2 import PdfReader
from pyhanko.sign import fields
from pyhanko.sign.signers import SimpleSigner
from pyhanko.pdf_utils.incremental_writer import IncrementalPdfFileWriter
# from pyhanko.stamp import ImageStampStyle
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .utils import is_ajax, classify_face
import base64
from django.core.files.base import ContentFile

# def add_image_signature(request):
#     if request.method == 'POST' and request.FILES['pdf_file'] and request.FILES['image_file']:
#         pdf_file = request.FILES['pdf_file']
#         image_file = request.FILES['image_file']

#         # Saving the uploaded files
#         fs = FileSystemStorage()
#         pdf_filename = fs.save(pdf_file.name, pdf_file)
#         image_filename = fs.save(image_file.name, image_file)

#         # Open the PDF file
#         pdf_input = open(fs.path(pdf_filename), 'rb')
#         pdf_reader = PyPDF2.PdfReader(pdf_input)
#         pdf_writer = PyPDF2.PdfWriter()

#         # Choose a page to add the image signature
#         page_num = 0  # Change this to your desired page number

#         # Open the image file
#         img = open(fs.path(image_filename), 'rb')

#         # Get the PDF page and merge the image
#         page = pdf_reader.getPage(page_num)
#         page.merge_page(PyPDF2.PdfReader(img).getPage(0))
#         pdf_writer.addPage(page)

#         # Save the modified PDF
#         output_filename = 'output.pdf'
#         with open(output_filename, 'wb') as output:
#             pdf_writer.write(output)

#         pdf_input.close()
#         img.close()

#         return render(request, 'success.html', {'output_filename': output_filename})

#     return render(request, 'add_image_signature.html')

# def add_image_signature(request):
#     try:
#         # Paths to PDF and image file
#         pdf_path = os.path.join(settings.MEDIA_ROOT, 'pdfs', 'System-Development-Method-With-The-Prototype-Method.pdf')
#         image_path = os.path.join(settings.MEDIA_ROOT, 'signatures', 'astra_avatar.png')

#         output_filename = 'output.pdf'

#         # Open the PDF file
#         pdf_input = open(pdf_path, 'rb')
#         pdf_reader = PyPDF2.PdfReader(pdf_input)
#         pdf_writer = PyPDF2.PdfWriter()

#         # Choose a page to add the image signature
#         page_num = 0  # Change this to your desired page number

#         # Open the image file
#         img = open(image_path, 'rb')

#         # Get the PDF page and merge the image
#         page = pdf_reader.pages[page_num]
#         img_page = PyPDF2.PdfReader(img).getPage(0)
        
#         # Ensure the image page has the required dimensions
#         img_page.mediaBox.upperRight = (
#             page.mediaBox.getUpperRight_x(),
#             page.mediaBox.getUpperRight_y()
#         )

#         page.merge_page(img_page)
#         pdf_writer.addPage(page)

#         # Save the modified PDF
#         output_path = os.path.join(settings.MEDIA_ROOT, output_filename)
#         with open(output_path, 'wb') as output:
#             pdf_writer.write(output)

#         pdf_input.close()
#         img.close()

#         output_url = os.path.join(settings.MEDIA_URL, output_filename)

#         return render(request, 'success.html', {'output_url': output_url})

#     except Exception as e:
#         # Handle exceptions, log errors, or display an error message
#         return render(request, 'esign/error.html', {'error_message': str(e)})

# def add_image_signature(request):
#     try:
#         # Paths to the main PDF and the watermark PDF
#         main_pdf_path = os.path.join(settings.MEDIA_ROOT, 'pdfs', 'Tunku_Abdul_Rahman_University_of_Management_and_Technology_TAR_UMT_-_Student_Intran_Xs7fVdR.pdf')
#         watermark_pdf_path = os.path.join(settings.MEDIA_ROOT, 'pdfs', 'watermark.pdf')

#         output_filename = 'output_with_watermark.pdf'

#         # Open the main PDF file
#         main_pdf_input = open(main_pdf_path, 'rb')
#         main_pdf_reader = PyPDF2.PdfReader(main_pdf_input)
#         main_pdf_writer = PyPDF2.PdfWriter()

#         # Open the watermark PDF file
#         watermark_pdf = open(watermark_pdf_path, 'rb')
#         watermark_pdf_reader = PyPDF2.PdfReader(watermark_pdf)
#         watermark_page = watermark_pdf_reader.pages[0]

#         # Merge each page of the main PDF on top of the watermark
#         for page_num in range(len(main_pdf_reader.pages)):
#             main_page = main_pdf_reader.pages[page_num]
#             main_page.merge_page(watermark_page)
#             main_pdf_writer.add_page(main_page)

#         # Save the modified PDF with the main content over the watermark
#         output_path = os.path.join(settings.MEDIA_ROOT, 'pdfs', output_filename)
#         with open(output_path, 'wb') as output:
#             main_pdf_writer.write(output)

#         main_pdf_input.close()
#         watermark_pdf.close()

#         output_url = os.path.join(settings.MEDIA_URL, 'pdfs', output_filename)

#         return render(request, 'esign/success.html', {'output_url': output_url})

#     except Exception as e:
#         return render(request, 'error.html', {'error_message': str(e)})

# def add_signature_to_pdf(request):
#     # Paths to your PDF and signature image
#     pdf_path = 'media/pdfs/default.pdf'
#     signature_image_path = 'media/signature/astra_avatar.png'

#     signer = SimpleSigner.load(request.user.certificate_path, request.user.private_key_path, chain_path=request.user.chain_path)

#     writer = IncrementalPdfFileWriter(open(pdf_path, 'rb'))
#     sig_field_name = 'signature_field_name'  # Replace with the field name in your PDF where you want to add the signature

#     # Load the PDF field where the signature will be placed
#     field = fields.SignatureFormField(sig_field_name)
#     field.embedder = writer
#     field.prepare_general(writer.reader)

#     # Prepare the image for the signature
#     signature_image = ImageStampStyle.from_file(signature_image_path)

#     # Sign the PDF
#     sig_field_appearance = signer.sign(
#         writer, field, signature_image=signature_image, existing_fields_only=True
#     )

#     # Save the modified PDF
#     with open('path/to/save/modified_document.pdf', 'wb') as modified_pdf:
#         writer.write_in_place(modified_pdf)
    
#     return HttpResponse('Signature added successfully')

from PyPDF2 import PdfReader
from pyhanko.sign import fields, signers
from pyhanko.sign.signers import SimpleSigner
from pyhanko.pdf_utils.incremental_writer import IncrementalPdfFileWriter
# from pyhanko.stamp import ImageStampStyle

# def add_image_signature(request):
#     # Paths to your PDF and signature image
#     pdf_path = 'media/pdfs/default.pdf'
#     signature_image_path = 'media/signature/astra_avatar.png'

#     signer = SimpleSigner.load(request.user.certificate_path, request.user.private_key_path, chain_path=request.user.chain_path)

#     writer = IncrementalPdfFileWriter(open(pdf_path, 'rb'))
#     sig_field_name = 'signature_field_name'  # Replace with the field name in your PDF where you want to add the signature

#     # Load the PDF field where the signature will be placed
#     field = fields.SignatureFormField(sig_field_name)
#     field.embedder = writer
#     field.prepare_general(writer.reader)

#     # Prepare the image for the signature
#     signature_image = ImageStampStyle.from_file(signature_image_path)

#     # Sign the PDF
#     sig_field_appearance = signer.sign(
#         writer, field, signature_image=signature_image, existing_fields_only=True
#     )

#     # Save the modified PDF
#     with open('media/pdfs//modified_document.pdf', 'wb') as modified_pdf:
#         writer.write_in_place(modified_pdf)
    
#     return HttpResponse('Signature added successfully')

from pyhanko import stamp
from pyhanko.pdf_utils import text, images
from pyhanko.pdf_utils.font import opentype
from pyhanko.pdf_utils.incremental_writer import IncrementalPdfFileWriter
from pyhanko.sign import fields, signers
from pyhanko.pdf_utils.layout import SimpleBoxLayoutRule, Margins, AxisAlignment
from pyhanko.pdf_utils.content import RawContent
from pyhanko.pdf_utils.reader import PdfFileReader
from pyhanko.sign.fields import SigFieldSpec
from django.contrib.gis.geoip2 import GeoIP2
from ipware import get_client_ip
from datetime import datetime, timedelta
import pytz

def add_image_signature(request):
    if request.method == 'POST':
        # Get the user's IP address
        client_ip = request.META.get('HTTP_X_FORWARDED_FOR', '180.75.247.19')
        # client_ip, _ = get_client_ip(request)

        # Get geolocation information based on the IP address
        if client_ip:
            geoip = GeoIP2()
            location = geoip.city(request.META.get('HTTP_X_FORWARDED_FOR', '180.75.247.19'))
            #  location = geoip.city(client_ip)
            geolocation_info = {
                'IP Address': client_ip,
                'City': location.get('city', ''),
                'Country': location.get('country_name', ''),
                'Region': location.get('region', ''),
            }
        else:
            geolocation_info = {
                'IP Address': 'N/A',
                'City': 'N/A',
                'Country': 'N/A',
                'Region': 'N/A',
            }

esign/templates/esign/display_pdf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Display PDF</title>
</head>
<body>
    <embed src="{{ pdf_url }}" type="application/pdf" width="100%" height="600px" />
</body>
</html>

esign/templates/esign/draw_signature.html
{% load static %}
{% csrf_token %}
<link rel="stylesheet" type="text/css"
    href="{% static 'css/draw_signature.css' %}">

<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="description" content="Signature Pad -created by Nijas">

        <meta name="viewport"
            content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">

        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">

        <link rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">        
        <style>
            #signature-options {
            display: flex;
            justify-content: center;
            }

            .signature-button {
                padding: 10px 20px;
                font-size: 16px;
                margin: 0 10px;
                cursor: pointer;
            }               
        </style>
    </head>
    <body>
        <div id="signature-pad" class="signature-pad">
            <div id="signature-options"
                style="text-align: center; padding: 20px;">
                <a href="{% url 'esign:type' %}">
                    <button class="signature-button" id="draw-signature-button">Type Signature</button>
                </a>
                <a href="{% url 'esign:draw' %}">
                    <button class="signature-button" id="draw-signature-button">Draw Signature</button>
                </a>
            </div>
            <div class="signature-pad--body">
                <canvas></canvas>
            </div>
            <div class="signature-pad--footer">
                <div class="description">Sign above</div>

                <div class="signature-pad--actions">
                    <div>
                        <button type="button" class="btn btn-default"
                            data-action="clear">Clear</button>
                        <button type="button" class="btn btn-default"
                            data-action="change-color">Change color</button>
                        <button type="button" class="btn btn-default"
                            data-action="undo">Undo</button>

                    </div>
                    <div>
                        <button type="button" class="button save"
                            data-action="save-svg" hidden=true></button>
                        <button type="button" class="button save"
                            data-action="save-png" hidden=true></button>
                        <button type="button" class="btn btn-primary"
                            style="background-color:blue" data-action="save-jpg">Done</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal" id="confirmationModal" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title">Confirmation</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  Do you want to proceed with face recognition to enhance the security of your signature?
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-primary" id="proceedWithFaceRecognitionButton">Yes</button>
                  <button type="button" class="btn btn-secondary" id="cancelFaceRecognitionButton" data-dismiss="modal">No</button>
                </div>
              </div>
            </div>
          </div>
        <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="{% static 'js/signature_pad.js'%}"></script>
        <script type="text/javascript" src="{% static 'js/app.js'%}"></script>
    </body>
</html>

esign/templates/esign/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error</title>
</head>
<body>
    <h1>An error occurred</h1>
    <p>{{ error_message }}</p>
</body>
</html>

esign/templates/esign/face_detection.html
{% extends 'esign/base.html' %}
{% load static %}

{% block scripts %}
<script type="text/javascript" src="{% static 'js/face_detection.js'%}" defer></script>
{% endblock scripts %}

{% block content %}
    <input type="hidden" id="user_id" value="{{ request.session.user_id }}">
    <section>
        <div id="verificationMessageContainer"></div>
    </section>
    <div class="text-center">
        <video autoplay="true" id="video-element"></video>
    </div>

    <div id="img-element"></div>

    <div class="text-center mt-3">
        <button class="btn btn-primary" id="capture-btn">take photo</button>
        <button class="btn btn-info" id="reload-btn">reload</button>
    </div> 
{% endblock content %}

esign/templates/esign/profile.html
{% load static %}
{% csrf_token %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile Page</title>
    <link rel="stylesheet" type="text/css"
    href="{% static 'css/profile.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
  </head>
<body>
    <div class="navbar-top">
        <div class="title">
            <h1>Profile</h1>
        </div>
        <ul>
            <li>
                <a href="{% url 'esign:index' %}">
                    <i class="fa fa-home fa-2x"></i>
                </a>
            </li>
            <li>  
                <a href="{% url 'esign:logout' %}">
                    <i class="fa fa-sign-out-alt fa-2x"></i>
                </a>
            </li>
        </ul>
      </div>

    <div class="sidenav">
        <div class="profile">
            <img src="{{ profile.photo.url }}" alt="user" width="100" height="100">
            <div class="name">
                {{ user.username }}
            </div>
            <div class="job">
                {{ user.position }}
            </div>
        </div>

        <div class="sidenav-url">
            <div class="url">
                <a href="#profile" class="active">Profile</a>
                <hr align="center">
            </div>
            <div class="url">
                <a href="{% url 'esign:upload' %}">Upload</a>
                <hr align="center">
            </div>
        </div>
    </div>

    <div class="main">
        <h2>IDENTITY</h2>
        <div class="card">
          <div class="card-body">
            <table id="profile-table">
              <tbody>
                <tr>
                  <td>User ID</td>
                  <td>:</td>
                  <td>{{ user.userID }}</td>
                </tr>
                <tr>
                  <td>Username</td>
                  <td>:</td>
                  <td>{{ user.username }}</td>
                </tr>
                <tr>
                  <td>Email</td>
                  <td>:</td>
                  <td>{{ user.email }}</td>
                </tr>
                <tr>
                  <td>Organization</td>
                  <td>:</td>
                  <td>{{ user.orgID.name }}</td>
                </tr>
                <tr>
                  <td>Bio</td>
                  <td>:</td>
                  <td>{{ profile.bio }}</td>
                </tr>
              </tbody>
            </table>        
          </div>
        </div>
      </div>
</body>
</html>

esign/templates/esign/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Success</title>
</head>
<body>
    <h1>Image added successfully!</h1>
    <p>The image signature has been added to the PDF file.</p>
    
    <!-- Download link for the modified PDF -->
    <p>Download your modified PDF: <a href="{{ output_url }}">Download PDF</a></p>
</body>
</html>

esign/templates/esign/type_signature.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport"
            content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">

        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">
        <title>Signature Maker</title>
        <link rel="stylesheet" type="text/css"
            href="{% static 'css/type_signature.css' %}">
        <link rel="stylesheet" type="text/css"
            href="{% static 'css/draw_signature.css' %}">
        <link rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
        <style>
     #signature-options {
            display: flex;
            justify-content: center;
        }

        .signature-button {
            padding: 10px 20px;
            font-size: 16px;
            margin: 0 10px;
            cursor: pointer;
        }
  </style>
    </head>
    <body>

        <div id="signature-pad" class="signature-pad">
            <div id="signature-options"
                style="text-align: center; padding: 20px;">
                <a href="{% url 'esign:type' %}">
                    <button class="signature-button" id="type-signature-button">Type
                        Signature</button>
                </a>
                <a href="{% url 'esign:draw' %}">
                    <button class="signature-button" id="draw-signature-button">Draw
                        Signature</button>
                </a>
            </div>
            <div class="signature-pad--body">
                <h1>Signature Maker</h1>
                <div class="form">
                    <input type="text" id="nameInput" placeholder="Your Name">
                    <select id="fontSelect">
                        <option value="Arial, sans-serif">Arial</option>
                        <option value="Times New Roman, serif">Times New Roman</option>
                        <option value="Verdana, sans-serif">Verdana</option>
                        <option value="Courier New, monospace">Courier New</option>
                        <option value="Georgia, serif">Georgia</option>
                        <option value="Trebuchet MS, sans-serif">Trebuchet MS</option>
                        <option value="Comic Sans MS, cursive">Comic Sans MS</option>
                        <option value="Impact, sans-serif">Impact</option>
                        <option value="Lucida Sans Unicode, sans-serif">Lucida Sans Unicode</option>
                    </select>
                    <button id="generateButton">Generate Signature</button>
                </div>
                <div class="signature" id="generatedSignature"></div>
                <!-- <button id="downloadButton" style="display: none">Download Signature</button> -->
            </div>
            <div class="signature-pad--footer">

                <div class="signature-pad--actions">
                    <div>
                        <button type="button" class="btn btn-default"
                            data-action="clear">Clear</button>
                        <button type="button" class="btn btn-default"
                            data-action="change-color">Change color</button>
                    </div>
                    <div>
                        <button type="button" class="button save"
                            data-action="save-svg" hidden=true></button>
                        <button type="button" class="button save"
                            data-action="save-png" hidden=true></button>
                        <button type="button" class="btn btn-primary"
                            style="background-color:blue" data-action="save-jpg">Done</button>
                    </div>
                </div>
            </div>
        </div>       
        <script type="text/javascript" src="{% static 'js/type.js'%}"></script>
    </body>
</html>

esign/templates/esign/upload_profile.html
{% extends 'esign/base.html' %}

{% block content %}
<div class="upload-profile-container">
  <h2>Upload Profile</h2>
  <form method="post" enctype="multipart/form-data" class="upload-profile-form">
    {% csrf_token %}
    <label for="{{ form.bio.id_for_label }}" class="form-label">Bio:</label>
    {{ form.bio }}
    {{ form.bio.errors }}

    <label for="{{ form.photo.id_for_label }}" class="form-label">Photo:</label>
    {{ form.photo }}
    {{ form.photo.errors }}

    <button type="submit" class="submit-button">Submit</button>
  </form>
</div>

  <style>
  body {
  font-family: Arial, sans-serif;
  background-color: #f4f4f4;
  margin: 0;
  padding: 0;
}

.upload-profile-container {
  max-width: 600px;
  margin: 50px auto;
  background-color: #fff;
  padding: 20px;
  border-radius: 8px;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
}

h2 {
  color: #333;
}

.upload-profile-form {
  margin-top: 20px;
}

.form-label {
  display: block;
  margin-bottom: 8px;
  color: #333;
}

input[type="file"] {
  display: block;
  margin-bottom: 16px;
}

.submit-button {
  background-color: #007bff;
  color: #fff;
  padding: 10px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

.submit-button:hover {
  background-color: #0056b3;
}
  </style>
{% endblock %}

esign/templates/esign/user_login.html
<!doctype html>
<html lang="en">
  <head>
  	<title>Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	
    {% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

	</head>
	<body class="img js-fullheight" style="background-image: url('{% static "images/香格里拉 雪山 打光.jpg" %}');">

	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 col-lg-4">
					<div class="login-wrap p-0">
		      	<h3 class="mb-4 text-center"><b>Member Login</b></h3>
		      	<form action="{% url 'esign:login' %}" class="signin-form" method="POST">
					{% if error %}
<div class="alert alert-danger" role="alert">
    {{ error }}
</div>
{% endif %}

					{% if messages %}
    {% for message in messages %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
                    {% csrf_token %}
		      		<div class="form-group">
		      			<input type="text" class="form-control" placeholder="Member ID" name="UID" required>
		      		</div>
	            <div class="form-group">
	              <input id="password-field" type="password" class="form-control" placeholder="Password" name="psw" required>
	              <span toggle="#password-field" class="fa fa-fw fa-eye field-icon toggle-password"></span>
	            </div>
	            <div class="form-group">
	            	<button type="submit" class="form-control btn btn-primary submit px-3">Sign In</button>
	            </div>
	            <div class="form-group d-md-flex">
	            	<div class="w-50">
								</div>
								<div class="w-50 text-md-right">
									<a href="#" style="color: #fff">Forgot Password</a>
								</div>
	            </div>
	          </form>
	          
		      </div>
				</div>
			</div>
		</div>
	</section>

	<!-- Bootstrap Modal for logout success -->
<div class="modal fade" id="logoutSuccessModal" tabindex="-1" role="dialog" aria-labelledby="logoutSuccessModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
	  <div class="modal-content">
		<div class="modal-header">
		  <h5 class="modal-title" id="logoutSuccessModalLabel">Logout Success</h5>
		  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		  </button>
		</div>
		<div class="modal-body">
		  You have successfully logged out.
		</div>
	  </div>
	</div>
  </div>

	<script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

    <!-- Trigger the modal on page load -->
  <!-- Bootstrap Modal for logout success -->
{% if show_logout_modal %}
<script>
  $(document).ready(function(){
    $('#logoutSuccessModal').modal('show');
  });
</script>
{% endif %}

	</body>
</html>